services:
    go-structured-error:
        build: .
        container_name: go-structured-error
        tty: true
        volumes:
            - .:/mount
        privileged: true
        command: /bin/sh
        working_dir: /mount
