# ./.github/workflows/golangci-lint.yml
name: golangci-lint (multi OS)

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - 'dev/**'

jobs:
    golangci-lint:
        strategy:
            matrix:
                go-version: ["1.22", "1.23", "1.24", "1.25"]
                os: [ubuntu-latest, macos-latest, windows-latest]
        uses: ./.github/workflows/.golangci-lint-reusable.yml
        with:
            os: ${{ matrix.os }}
            go-version: ${{ matrix.go-version }}
            golangci-lint-version: v2.5
